server:
  port: 8089
spring:
  datasource:
    url: jdbc:mysql://192.168.1.4:3306/tb_hotel?useSSL=false
    username: root
    password: M2M123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: 192.168.1.4
    port: 5672
    virtual-host: /
    username: admin
    password: admin
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.xn2001.hotel.pojo